### ISSUE TITLE
Delete NAR champ-source-data bucket and cmsource

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/Program#22]
All of this applies to the NAR account

I think we can safely delete `s3://champ-source-data` now since the sync is working and it exists on Carol's account

Likewise I think we can delete the `CMSource` dir in `s3://champdata` since that's just unzipped data from `champ-source-data` and not in use by anyone.

Also I think we can take down the  CSV API reading off of Dynamodb and wipe all the dynamodb tables. They're super stale and not that useful. I will check with carol first.

@philipbaileynar check the boxes you agree with:

- [x] **DELETE** `s3://champ-source-data`
- [x] **DELETE** `s3://champdata/CMSource` (we leave `/QA` alone for now
- [x] **DELETE** DynamoDB Tables
- [x] **DELETE** `s3://champ-source-data` CSV API Gateway

This should save us several $$$ per day

**Comment by philipbaileynar** [comment]
@MattReimer you and your fancy checkboxes...

**Comment by MattReimer** [comment]
Ok. I will proceed with this after I double check with Carol.

**Comment by MattReimer** [comment]
It is done. We should notice the billing shift in 24-48 hours
