### ISSUE TITLE
Ensure that topo projects can be uploaded through RAVE

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/Program#24]
Geoff Stevens at USU is about to run several historical visits through the 2017 toolbar. The goal is to have these visits available to users in RAVE.

Please ensure that RAVE can upload a Topo toolbar project in the correct place in the warehouse.

I have uploaded a sample TopoData project onto the NAR Drive at:

`Projects\CHaMP\2017_07_03_TopoData.zip`

This can be faked to be any watershed and site for the purposes of proving the upload.

**Comment by MattReimer** [comment]
We're going to need some changes to the XML:

``` xml
    <Meta name="SiteName">Test Site</Meta>
    <Meta name="VisitID">1</Meta>
    <Meta name="FieldSeason">2017</Meta>

needs to become...

    <Meta name="Site">Test Site</Meta>
    <Meta name="Visit">1</Meta>
    <Meta name="Year">2017</Meta>
```

Or riverscapes needs to change... Let's talk

**Comment by MattReimer** [comment]
I need a change to the project tag too:

```
<Project>
Needs to be...
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XSD/V1/Project.xsd">
  <Name>Testing Project</Name>

```

**Comment by MattReimer** [comment]
I can confirm that the next version of RAVE will be fully capable of uploading Topo projects

**Comment by philipbaileynar** [comment]
Topo Toolbar version 6.0.19 has these changes implemented.
