### ISSUE TITLE
<Analysis> Vs. <Analyses>

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/Program#4]
It seems like some of us are using `<Analysis>` and others are using `<
Analyses>`.

I'm sorry I didn't catch it sooner but we probably need to agree on one. 

Discuss then let's get it changed.

**Comment by KellyMWhitehead** [comment]
I consider each entity as an "anaysis", so they would be grouped in the plural "analyses" tag. 

-KW

**Comment by MattReimer** [comment]
I agree @KellyMWhitehead:

``` xml
<Analyses>
   <GNATAnalysis>
   </GNATAnalysis>
</Analyses>
```

Just to be clear here, multiple analyses is for different types of analysis, not multiples of the same analysis..... or is it?

**Comment by KellyMWhitehead** [comment]
Could be multiple of either same type or different types.

**Comment by jtgilbert** [comment]
I've just been using <analysis> with different <outputs> inside of each analysis.  I have not grouped them into <analyses>

**Comment by MattReimer** [comment]
Ok. I think based on this we should use:

```
<Analyses>
   <GNATAnalysis>
   </GNATAnalysis>
</Analyses>
```

or 

```
<Analyses>
   <Analysis>
   </Analysis>
</Analyses>
```

The important thing is the grouping of `<Analyses>`. What goes inside that can be customized to what your tool needs. 

Objections?

**Comment by jesselangdon** [comment]
How do we differentiate each `<Analysis>` node?  Just by a name parameter?

**Comment by MattReimer** [comment]
Good question.... 

My preference in all this would be to only have multiple analysis *"types"* so maybe:

```
<Analyses>
   <GNATPreAnalysis>
   </GNATPreAnalysis>
   <GNATVolumetricAnalysis>
   </GNATVolumetricAnalysis>
</Analyses>
```

(I'm totally making up the names btw)

Maybe we shouldn't allow generic `<Analysis>` nodes?

**Comment by jesselangdon** [comment]
I think that makes more sense.  Otherwise, I'd assume we need to have an `ID` or `type` parameter in each `Analysis` node.

**Comment by MattReimer** [comment]
Ok. I'm going to run this by @joewheaton and get back to you. I want to make sure we nail this then I'll send out an email and update the documentation.

**Comment by MattReimer** [comment]
Ok. After talking to @joewheaton Here's the official guidance and I'll update the docs to reflect it 

### IF you have one analysis type it's easy:

``` xml
<Analyses>
   <Analysis>
            <Name>Hydro Analysis</Name>
            <Metrics/>
            <Outputs/>
   </Analysis>
</Analyses>
```

You can also name it if you want:

``` xml
<Analyses>
   <MyAnalysis>
            <Name>Hydro Analysis</Name>
            <Metrics/>
            <Outputs/>
   </MyAnalysis>
</Analyses>
```

### If you have multiple Analysis Types you MUST name them

``` xml
<Analyses>
   <MyAnalysis1>
            <Name>Hydro Analysis</Name>
            <Metrics/>
            <Outputs/>
   </MyAnalysis1>
   <MyAnalysis2>
            <Name>Hydro Analysis</Name>
            <Metrics/>
            <Outputs/>
   </MyAnalysis2>
</Analyses>
```
Please use more descriptive names than `MyAnalysis1`. 

### You can't have multiple analyses of the same type inside `<Analyses>`

That's what realizations are for so you'll need a new realization.
