### ISSUE TITLE
XML Filename

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/Program#5]
Right now we have some inconsistency with what the XML files are actually called. 

There is a strong case for making them all: `project.xml`

so that we can easily collect them all. 

Thoughts?

**Comment by jesselangdon** [comment]
Agreed. Let's call them all `project.xml`

**Comment by MattReimer** [comment]
Ok. Just chatted with @joewheaton. We're going to go with the following:

## `project.rs.xml`

The `.rs.` namespacing is so that we don't have collisions with anybody else calling some file `project.xml` by accident and then colliding with us
