### ISSUE TITLE
Project documentation/packaging for projects spanning multiple HUCs 

### ISSUE THREAD

**Issue by volkcj** [Riverscapes/Program#6]
We have several upcoming projects that have analysis products spanning multiple HUCs.  Is there project documentation to define which HUCS are covered by these broad datasets?  How will these be presented as 'available' projects for a RAVE user?
#
- Extrapolations/Imputations (Matt Nahorniak, likely Pete McHugh as well)
- QRF (Kevin See)
- Restoration Projects (Monica Diaz)
- Salmon Population Survey (SPS Estimates- Monica Diaz).

**Comment by MattReimer** [comment]
This is an excellent question @volkcj and my answer is: "I don't know"

If something spans multiple HUCs does that mean it spans all available HUCs or are there specific groupings we're trying to capture?

I though the Extrapolations/Imputations would work by rolling up everything below them in the hierarchy. If that's not the case we need to discuss. 

I'm going to meet with Monica next week and start sorting this out so I may have to get back to you after I talk to her before we go any farther.

**Comment by volkcj** [comment]
Monica's dataset is a good place to start.  There are a few different forms of the issue that might have different solutions, too.  Here's some more info about the different forms:
- Data extent spans multiple HUCs, but points/values within HUCs aren't dependent on data from the other HUCs.  In other words, the data are managed at a regional extent, but could be split to HUCs (Restoration data is in this category)
-Inputs require multiple HUCs of data, but Analysis outputs are not dependent on the HUC.  This is the case for extrapolation.  Data from all HUCs are used to generate the models estimating results for all HUCs.
-Outputs extent across multiple HUCs and are dependent on each other.  The Salmon Population Survey (SPS) data fits into this category.  Estimates are made on fish population boundaries, which do not always nicely align with HUCs and they can't be split by HUC boundaries in an additive fashion.  

I'm guessing we might have a short term solution of chucking these into 'context' layers or filing relevant outputs by dominant HUC but letting extents traverse HUC boundaries, but we'll need to eventually deal with a long term solution for storing and accessing these in the warehouse.

**Comment by MattReimer** [comment]
I'm going to close this issue since we talked about it and open up a bigger, more specific one.
