### ISSUE TITLE
Additional watershed option needed

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/Program#8]
In the xml Watershed collection options, please include the watershed "Middle Salmon-Panther", HUC ID 17060203. Thanks!
https://cfpub.epa.gov/surf/huc.cfm?huc_code=17060203

**Comment by MattReimer** [comment]
It is done see the following commit: https://github.com/Riverscapes/Program/commit/2e23a79b88a99408b6bdb53d0210697aba4bc40c
