### ISSUE TITLE
Need CRB-wide Projects

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/Program#9]
The need to have Projects that can act at the `Region` level of ("CRB" in this case) is one that was mentioned but may have gotten overlooked in the design.

We can fix this but it's going to mean moving data.

### The bump

In terms of file system everything Gets Bumped so...

```
CRB/Asotin/Network/Solar/project.rs.xml

Changes to.....

CRB/Watershed/Asotin/Network/Solar/project.rs.xml
```

### CRB-level products

We can now have products at the scale greater than a watershed
```
CRB/QRF/project.rs.xml
```

### Site-Level Products (Note the order: "Site/Year/YYYY/VID/Flow/S000002")

Flow-level products are the deepest we have so far:

```
CRB/Watershed/Asotin/Site/CBW00123123/Year/2011/VISIT_123/Flow/S000002/Hydro/project.rs.xml
```

Topo Toolbar projects live here:

```
CRB/Watershed/Asotin/Site/CBW00123123/Year/2011/VISIT_123/Topo/project.rs.xml
```

This structure allows us to have site-level products here:

```
CRB/Watershed/Asotin/Site/CBW00123123/Hydro/project.rs.xml
CRB/Watershed/Asotin/Site/CBW00123123/FHM/project.rs.xml
```

**Comment by philipbaileynar** [comment]
I think I understand the examples provided, but it would help to see an example of a CRB-wide dataset in the proposed examples. I just see existing watersheds moving. I think...

**Comment by MattReimer** [comment]
Good catch @philipbaileynar I've added a couple of totally fictitious NOAA products that theoritically apply region-wide to show how that would go.

**Comment by MattReimer** [comment]
@philipbaileynar and @volkcj maybe you could just review this briefly since it's kind of hard to undo once it's done.

**Comment by volkcj** [comment]
looks good.  Hydro projects need some shuffling if they're moving from visit to site based products--they are functioning as site based products, but that wasn't an option at the time.  Need to add a ticket to revamp the existing hydro project xmls if that's the case.

**Comment by MattReimer** [comment]
Carol, Hydro exists in two places:

```
CRB/Watershed/Asotin/Site/CBW00123123/Hydro/project.rs.xml
```
this is the hydro site rollup. We don't have a mechanism for this yet.

Regular hydro products will live here:
```
CRB/Watershed/Asotin/Site/CBW00123123/Year/2011/VISIT_123/Flow/S000000123/Hydro/project.rs.xml
```

**Comment by MattReimer** [comment]
Just for fun here's a simulation of every conceivable project in riverscapes:

[Riverscapes.txt](https://github.com/Riverscapes/Program/files/1122858/Riverscapes.txt)
